name: ceu_course
channels:
  - defaults
dependencies:
  - bleach=1.5.0=py36_0
  - colorama=0.3.9=py36_0
  - cycler=0.10.0=py36_0
  - decorator=4.1.2=py36_0
  - entrypoints=0.2.3=py36_0
  - graphviz=2.38.0=4
  - ipykernel=4.6.1=py36_0
  - ipython=6.1.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=6.0.0=py36_0
  - jedi=0.10.2=py36_2
  - jinja2=2.9.6=py36_0
  - jsonschema=2.6.0=py36_0
  - jupyter=1.0.0=py36_3
  - jupyter_client=5.1.0=py36_0
  - jupyter_console=5.2.0=py36_0
  - jupyter_core=4.3.0=py36_0
  - markupsafe=1.0=py36_0
  - matplotlib=2.0.2=np113py36_0
  - mistune=0.7.4=py36_0
  - mkl=2017.0.3=0
  - nbconvert=5.2.1=py36_0
  - nbformat=4.4.0=py36_0
  - networkx=1.11=py36_0
  - notebook=5.0.0=py36_0
  - numpy=1.13.1=py36_0
  - pandas=0.20.3=py36_0
  - pandocfilters=1.4.2=py36_0
  - path.py=10.3.1=py36_0
  - patsy=0.4.1=py36_0
  - pickleshare=0.7.4=py36_0
  - pip=9.0.1=py36_1
  - plotly=2.0.11=py36_0
  - prompt_toolkit=1.0.15=py36_0
  - pydotplus=2.0.2=py36_0
  - pygments=2.2.0=py36_0
  - pyparsing=2.2.0=py36_0
  - pyqt=5.6.0=py36_2
  - python=3.6.2=0
  - python-dateutil=2.6.1=py36_0
  - python-graphviz=0.5.2=py36_0
  - pytz=2017.2=py36_0
  - pyzmq=16.0.2=py36_0
  - qtconsole=4.3.1=py36_0
  - requests=2.14.2=py36_0
  - scikit-learn=0.19.0=np113py36_0
  - scipy=0.19.1=np113py36_0
  - seaborn=0.8=py36_0
  - simplegeneric=0.8.1=py36_1
  - sip=4.18=py36_0
  - six=1.10.0=py36_0
  - statsmodels=0.8.0=np113py36_0
  - testpath=0.3.1=py36_0
  - tornado=4.5.2=py36_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - wheel=0.29.0=py36_0
  - widgetsnbextension=2.0.0=py36_0
  - pip:
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.4.0
    - jupyter-highlight-selected-word==0.1.0
    - jupyter-latex-envs==1.4.1
    - jupyter-nbextensions-configurator==0.4.0
    - ldap3==2.5.1
    - lxml==4.1.1
    - nbextensions==0.0.6
    - pyasn1==0.4.2
    - pyyaml==3.12

